batch_size: 100
clip: 5
dataroot: /data/big.txt
experiment_desc: test_model
model: {drop_prob: 0.3, grad_clip: 5, loss: ceLoss, model_n: semichar_rnn, n_hidden: 650,
  n_layers: 2}
num_epochs: 20
optimizer: {lr: 0.003, name: adam}
print_every: 100
seq_lenght: 50
